source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'STOptimizedUIButton_Example', :exclusive => true do
  pod "STOptimizedUIButton", :path => "../"
end

target 'STOptimizedUIButton_Tests', :exclusive => true do
  pod "STOptimizedUIButton", :path => "../"

  
end
